### ISSUE TITLE
Legion timer header for candy bar is on when LDB mode is selected

### ISSUE THREAD

**Issue by esvarc** [funkydude/LegionInvasionTimer#55] opened 2017-05-03 12:52 UTC
If LDB mode is pikced without locking up window with canfybars, then header is always shown on sceen because legionTimerDB.lock never become true, is not possible to lock it when LDB mode is ticked in options

```
	if legionTimerDB.lock then
		f:EnableMouse(false)
		f.bg:Hide()
		f.header:Hide()
	end
```

**Comment by esvarc** [comment] 2017-05-03 12:55
LDB plugin libraries are not included in package and not listed in embeds.xml, in code is library required by:

`local ls = LibStub("LibDataBroker-1.1", true)`

This library is dnymaicaly registered only after bar starts, but it need to be inicialized at load or it will not be recognized by addons supporting LDB like ElvUI, becaause list of available LDB sources is checked on application load. This change in code fix it:

`do
	local ls = LibStub("LibDataBroker-1.1", true)
	local obj = ls:NewDataObject("LegionInvasionTimer", {type = "data source", icon = 132177, text = "..."})
       	function obj.OnTooltipShow(tooltip)
       		if not tooltip or not tooltip.AddLine or not tooltip.AddDoubleLine then return end
       		ShowTip(tooltip)
       	end
	local prevTime, label, repeater = 0, "", false
	local function update()
		prevTime = prevTime - 60
		obj.text = label..": ".. SecondsToTime(prevTime, true)
	end
	startBroker = function(text, timeLeft, icon)
		if obj then
			obj.icon = icon
			obj.text = text..": ".. SecondsToTime(timeLeft, true)
			prevTime = timeLeft
			label = text
			if repeater then repeater:Cancel() end
			repeater = C_Timer.NewTicker(60, update)
		end
	end
end
`

**Comment by funkydude** [comment] 2017-05-03 14:35
Not seeing the problem here. As soon as you choose LDB mode the option is set to locked.
https://github.com/funkydude/LegionInvasionTimer/blob/master/Options/Options.lua#L376

Cannot reproduce. Working perfectly fine here. As soon as I swap from bar to data broker mode, it's locked.

**Comment by esvarc** [comment] 2017-05-03 15:05
You can reproduce it easy. Switch back to candy bar mode, untick locked. Then selcet LDB mode mode. And you will see what happens, there will be header and you can't tick locked because option is greyed.

Solution is when you code auto lock in moment when LDB mode is selected.

**Comment by funkydude** [comment] 2017-05-03 15:08
Here is what I did:
Switch to LDB
Switch back to Bar
Untick "lock"
Switch to LDB

It is correctly locked, am I missing a step?

**Comment by funkydude** [comment] 2017-05-03 17:07
Closing, cannot reproduce. Recommending BugSack if you wish to further debug it, as I suspect you may be encountering an error.

**Closed as completed by funkydude** 2017-05-03 17:07 UTC

**Comment by esvarc** [comment] 2017-05-03 18:02
Not exactly. Here are two pictures how it behave at my client. 1st picture show before I pick data-broker and 2nd how it looks on screen and when I use /lit ro see settings.
![data-broker-with-lock-unticked](https://cloud.githubusercontent.com/assets/6427670/25674477/35d729f2-303b-11e7-83b9-fba454e3568d.jpg)
![switch-to-data-broker](https://cloud.githubusercontent.com/assets/6427670/25674478/35d975ea-303b-11e7-933e-8eb2593d5b7b.jpg)

I found may be reason where problem is. I had LUA variables in LegionInvasionTimer.lua  from 1st release, when I did erase stored LUA variables it did with same steps to reproduce next two pictures.

**Comment by esvarc** [comment] 2017-05-03 18:06
After I did purge LegionInvasionTimer.lua  in WTF folder.

![fresh-without-lua-variables-in-wtf](https://cloud.githubusercontent.com/assets/6427670/25674650/f15f959c-303b-11e7-9649-9cba5a9f758f.jpg)
![ok-after-switch-to-data-broker-without-old-lua-variables](https://cloud.githubusercontent.com/assets/6427670/25674649/f15ec4f0-303b-11e7-931f-98e2e5200d41.jpg)

As you can see green title with "LegionInvasionTimer" is gone as should be. I found that in my old LUA variables was really **["lock"] = false**

**Comment by funkydude** [comment] 2017-05-03 18:12
Having the old settings wouldn't make any difference. It was always called "lock", it hasn't changed since last year. The code specifically sets lock to true and then reloads your UI. I have no clue why lock wasn't being set to true for you when the option was changed, or why suddenly it now is. Maybe you had some read-only problem with the settings.
